### ISSUE TITLE
UI switch to generate the full set of fields defined in schema

### ISSUE THREAD

**Issue by revelt** [json-schema-faker/website-jsf#19]
Hi all,

First of all, thanks for all your great work on this.

Currently the keys are chosen at random and it's fine. However, when working with HTML templates that consume the data coming from the JSON API, I need to generate a dummy data JSON file with all the possible keys defined in the schema. Only then I can properly check, are all fields within HTML pulling the JSON values right and pulling from the right keys.

This is separate from the actual JS library implementation, which I believe should exist in the main repo's issues.

cheers
Roy

**Comment by pateketrueke** [comment]
Hi, this is already solved on the main library by enabling the `alwaysFakeOptional` _option_.

The website is currently updated to allow those settings too.

Thanks for your feedback!

**Comment by revelt** [comment]
Thanks!
