### ISSUE TITLE
Errors in using chance and faker since v0.4.5 and upwards

### ISSUE THREAD

**Issue by osher** [json-schema-faker/website-jsf#33]
The following demos do not work with verisons higher than 0.4.3 (i.e 0.4.5 and 0.4.6).

RC versions of 0.5 do work - however, it's not a release version and is not installed by default by NPM.
A latest 0.4.X that works with faker is needed

**Comment by osher** [comment]
Just to make sure the fix propagates when it's done 😅 
https://github.com/json-schema-faker/json-schema-faker/issues/363

**Comment by pateketrueke** [comment]
This is already fixed on the website version, sadly those tags are broken for consumption over cdnjs and bower (due missing third-party deps).
